package cn.xidu.app.mapper;

import cn.xidu.app.entity.APP_ACTIVE;
import cn.xidu.app.entity.APP_ACTIVEExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface APP_ACTIVEMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int countByExample(APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int deleteByExample(APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int insert(APP_ACTIVE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int insertSelective(APP_ACTIVE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    List<APP_ACTIVE> selectByExampleWithBLOBs(APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    List<APP_ACTIVE> selectByExample(APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    APP_ACTIVE selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") APP_ACTIVE record, @Param("example") APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") APP_ACTIVE record, @Param("example") APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByExample(@Param("record") APP_ACTIVE record, @Param("example") APP_ACTIVEExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByPrimaryKeySelective(APP_ACTIVE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(APP_ACTIVE record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_active
     *
     * @mbggenerated Mon Sep 19 15:51:15 CST 2016
     */
    int updateByPrimaryKey(APP_ACTIVE record);
}