package cn.xidu.app.mapper;

import cn.xidu.app.dto.banner.APP_BANNER_Dto;
import cn.xidu.app.dto.banner.APP_BANNER_DtoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface APP_BANNER_DtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int countByExample(APP_BANNER_DtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int deleteByExample(APP_BANNER_DtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int insert(APP_BANNER_Dto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int insertSelective(APP_BANNER_Dto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    List<APP_BANNER_Dto> selectByExample(APP_BANNER_DtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    APP_BANNER_Dto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") APP_BANNER_Dto record, @Param("example") APP_BANNER_DtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int updateByExample(@Param("record") APP_BANNER_Dto record, @Param("example") APP_BANNER_DtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int updateByPrimaryKeySelective(APP_BANNER_Dto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info_banner
     *
     * @mbggenerated Wed Sep 21 15:50:50 CST 2016
     */
    int updateByPrimaryKey(APP_BANNER_Dto record);
}