package cn.entity.test;

public class TEST_YZM_MobileCodeWithBLOBs extends TEST_YZM_MobileCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_yzm_mobilecode.referer
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_yzm_mobilecode.linksource
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    private String linksource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_yzm_mobilecode.referer
     *
     * @return the value of xd_yzm_mobilecode.referer
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_yzm_mobilecode.referer
     *
     * @param referer the value for xd_yzm_mobilecode.referer
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    public void setReferer(String referer) {
        this.referer = referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_yzm_mobilecode.linksource
     *
     * @return the value of xd_yzm_mobilecode.linksource
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    public String getLinksource() {
        return linksource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_yzm_mobilecode.linksource
     *
     * @param linksource the value for xd_yzm_mobilecode.linksource
     *
     * @mbggenerated Mon Sep 05 15:58:15 CST 2016
     */
    public void setLinksource(String linksource) {
        this.linksource = linksource;
    }
}