package cn.entity.qdm0020530;

public class DEDE_ADDONARTICLE {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.aid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.typeid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private Short typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.redirecturl
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private String redirecturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.templet
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private String templet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.userip
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private String userip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_addonarticle.body
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    private String body;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.aid
     *
     * @return the value of dede_addonarticle.aid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.aid
     *
     * @param aid the value for dede_addonarticle.aid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.typeid
     *
     * @return the value of dede_addonarticle.typeid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.typeid
     *
     * @param typeid the value for dede_addonarticle.typeid
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.redirecturl
     *
     * @return the value of dede_addonarticle.redirecturl
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public String getRedirecturl() {
        return redirecturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.redirecturl
     *
     * @param redirecturl the value for dede_addonarticle.redirecturl
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setRedirecturl(String redirecturl) {
        this.redirecturl = redirecturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.templet
     *
     * @return the value of dede_addonarticle.templet
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public String getTemplet() {
        return templet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.templet
     *
     * @param templet the value for dede_addonarticle.templet
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setTemplet(String templet) {
        this.templet = templet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.userip
     *
     * @return the value of dede_addonarticle.userip
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public String getUserip() {
        return userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.userip
     *
     * @param userip the value for dede_addonarticle.userip
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setUserip(String userip) {
        this.userip = userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_addonarticle.body
     *
     * @return the value of dede_addonarticle.body
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_addonarticle.body
     *
     * @param body the value for dede_addonarticle.body
     *
     * @mbggenerated Thu Sep 08 11:21:11 CST 2016
     */
    public void setBody(String body) {
        this.body = body;
    }
}