package cn.entity.qdm0020530;

import java.util.ArrayList;
import java.util.List;

public class DEDE_ARCHIVESExample {
    
	protected int offset;
	protected int size; 
	
	public int getOffset() {
		return offset;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public DEDE_ARCHIVESExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNull() {
            addCriterion("typeid is null");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNotNull() {
            addCriterion("typeid is not null");
            return (Criteria) this;
        }

        public Criteria andTypeidEqualTo(Short value) {
            addCriterion("typeid =", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotEqualTo(Short value) {
            addCriterion("typeid <>", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThan(Short value) {
            addCriterion("typeid >", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThanOrEqualTo(Short value) {
            addCriterion("typeid >=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThan(Short value) {
            addCriterion("typeid <", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThanOrEqualTo(Short value) {
            addCriterion("typeid <=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidIn(List<Short> values) {
            addCriterion("typeid in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotIn(List<Short> values) {
            addCriterion("typeid not in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidBetween(Short value1, Short value2) {
            addCriterion("typeid between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotBetween(Short value1, Short value2) {
            addCriterion("typeid not between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeid2IsNull() {
            addCriterion("typeid2 is null");
            return (Criteria) this;
        }

        public Criteria andTypeid2IsNotNull() {
            addCriterion("typeid2 is not null");
            return (Criteria) this;
        }

        public Criteria andTypeid2EqualTo(String value) {
            addCriterion("typeid2 =", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2NotEqualTo(String value) {
            addCriterion("typeid2 <>", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2GreaterThan(String value) {
            addCriterion("typeid2 >", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2GreaterThanOrEqualTo(String value) {
            addCriterion("typeid2 >=", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2LessThan(String value) {
            addCriterion("typeid2 <", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2LessThanOrEqualTo(String value) {
            addCriterion("typeid2 <=", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2Like(String value) {
            addCriterion("typeid2 like", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2NotLike(String value) {
            addCriterion("typeid2 not like", value, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2In(List<String> values) {
            addCriterion("typeid2 in", values, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2NotIn(List<String> values) {
            addCriterion("typeid2 not in", values, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2Between(String value1, String value2) {
            addCriterion("typeid2 between", value1, value2, "typeid2");
            return (Criteria) this;
        }

        public Criteria andTypeid2NotBetween(String value1, String value2) {
            addCriterion("typeid2 not between", value1, value2, "typeid2");
            return (Criteria) this;
        }

        public Criteria andSortrankIsNull() {
            addCriterion("sortrank is null");
            return (Criteria) this;
        }

        public Criteria andSortrankIsNotNull() {
            addCriterion("sortrank is not null");
            return (Criteria) this;
        }

        public Criteria andSortrankEqualTo(Integer value) {
            addCriterion("sortrank =", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankNotEqualTo(Integer value) {
            addCriterion("sortrank <>", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankGreaterThan(Integer value) {
            addCriterion("sortrank >", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankGreaterThanOrEqualTo(Integer value) {
            addCriterion("sortrank >=", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankLessThan(Integer value) {
            addCriterion("sortrank <", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankLessThanOrEqualTo(Integer value) {
            addCriterion("sortrank <=", value, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankIn(List<Integer> values) {
            addCriterion("sortrank in", values, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankNotIn(List<Integer> values) {
            addCriterion("sortrank not in", values, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankBetween(Integer value1, Integer value2) {
            addCriterion("sortrank between", value1, value2, "sortrank");
            return (Criteria) this;
        }

        public Criteria andSortrankNotBetween(Integer value1, Integer value2) {
            addCriterion("sortrank not between", value1, value2, "sortrank");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("flag like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("flag not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andIsmakeIsNull() {
            addCriterion("ismake is null");
            return (Criteria) this;
        }

        public Criteria andIsmakeIsNotNull() {
            addCriterion("ismake is not null");
            return (Criteria) this;
        }

        public Criteria andIsmakeEqualTo(Short value) {
            addCriterion("ismake =", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeNotEqualTo(Short value) {
            addCriterion("ismake <>", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeGreaterThan(Short value) {
            addCriterion("ismake >", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeGreaterThanOrEqualTo(Short value) {
            addCriterion("ismake >=", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeLessThan(Short value) {
            addCriterion("ismake <", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeLessThanOrEqualTo(Short value) {
            addCriterion("ismake <=", value, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeIn(List<Short> values) {
            addCriterion("ismake in", values, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeNotIn(List<Short> values) {
            addCriterion("ismake not in", values, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeBetween(Short value1, Short value2) {
            addCriterion("ismake between", value1, value2, "ismake");
            return (Criteria) this;
        }

        public Criteria andIsmakeNotBetween(Short value1, Short value2) {
            addCriterion("ismake not between", value1, value2, "ismake");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(Short value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(Short value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(Short value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(Short value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(Short value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(Short value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<Short> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<Short> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(Short value1, Short value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(Short value1, Short value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andArcrankIsNull() {
            addCriterion("arcrank is null");
            return (Criteria) this;
        }

        public Criteria andArcrankIsNotNull() {
            addCriterion("arcrank is not null");
            return (Criteria) this;
        }

        public Criteria andArcrankEqualTo(Short value) {
            addCriterion("arcrank =", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankNotEqualTo(Short value) {
            addCriterion("arcrank <>", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankGreaterThan(Short value) {
            addCriterion("arcrank >", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankGreaterThanOrEqualTo(Short value) {
            addCriterion("arcrank >=", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankLessThan(Short value) {
            addCriterion("arcrank <", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankLessThanOrEqualTo(Short value) {
            addCriterion("arcrank <=", value, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankIn(List<Short> values) {
            addCriterion("arcrank in", values, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankNotIn(List<Short> values) {
            addCriterion("arcrank not in", values, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankBetween(Short value1, Short value2) {
            addCriterion("arcrank between", value1, value2, "arcrank");
            return (Criteria) this;
        }

        public Criteria andArcrankNotBetween(Short value1, Short value2) {
            addCriterion("arcrank not between", value1, value2, "arcrank");
            return (Criteria) this;
        }

        public Criteria andClickIsNull() {
            addCriterion("click is null");
            return (Criteria) this;
        }

        public Criteria andClickIsNotNull() {
            addCriterion("click is not null");
            return (Criteria) this;
        }

        public Criteria andClickEqualTo(Integer value) {
            addCriterion("click =", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickNotEqualTo(Integer value) {
            addCriterion("click <>", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickGreaterThan(Integer value) {
            addCriterion("click >", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickGreaterThanOrEqualTo(Integer value) {
            addCriterion("click >=", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickLessThan(Integer value) {
            addCriterion("click <", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickLessThanOrEqualTo(Integer value) {
            addCriterion("click <=", value, "click");
            return (Criteria) this;
        }

        public Criteria andClickIn(List<Integer> values) {
            addCriterion("click in", values, "click");
            return (Criteria) this;
        }

        public Criteria andClickNotIn(List<Integer> values) {
            addCriterion("click not in", values, "click");
            return (Criteria) this;
        }

        public Criteria andClickBetween(Integer value1, Integer value2) {
            addCriterion("click between", value1, value2, "click");
            return (Criteria) this;
        }

        public Criteria andClickNotBetween(Integer value1, Integer value2) {
            addCriterion("click not between", value1, value2, "click");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Short value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Short value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Short value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Short value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Short value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Short> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Short> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Short value1, Short value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Short value1, Short value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andShorttitleIsNull() {
            addCriterion("shorttitle is null");
            return (Criteria) this;
        }

        public Criteria andShorttitleIsNotNull() {
            addCriterion("shorttitle is not null");
            return (Criteria) this;
        }

        public Criteria andShorttitleEqualTo(String value) {
            addCriterion("shorttitle =", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotEqualTo(String value) {
            addCriterion("shorttitle <>", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleGreaterThan(String value) {
            addCriterion("shorttitle >", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleGreaterThanOrEqualTo(String value) {
            addCriterion("shorttitle >=", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLessThan(String value) {
            addCriterion("shorttitle <", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLessThanOrEqualTo(String value) {
            addCriterion("shorttitle <=", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleLike(String value) {
            addCriterion("shorttitle like", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotLike(String value) {
            addCriterion("shorttitle not like", value, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleIn(List<String> values) {
            addCriterion("shorttitle in", values, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotIn(List<String> values) {
            addCriterion("shorttitle not in", values, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleBetween(String value1, String value2) {
            addCriterion("shorttitle between", value1, value2, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andShorttitleNotBetween(String value1, String value2) {
            addCriterion("shorttitle not between", value1, value2, "shorttitle");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andWriterIsNull() {
            addCriterion("writer is null");
            return (Criteria) this;
        }

        public Criteria andWriterIsNotNull() {
            addCriterion("writer is not null");
            return (Criteria) this;
        }

        public Criteria andWriterEqualTo(String value) {
            addCriterion("writer =", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterNotEqualTo(String value) {
            addCriterion("writer <>", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterGreaterThan(String value) {
            addCriterion("writer >", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterGreaterThanOrEqualTo(String value) {
            addCriterion("writer >=", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterLessThan(String value) {
            addCriterion("writer <", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterLessThanOrEqualTo(String value) {
            addCriterion("writer <=", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterLike(String value) {
            addCriterion("writer like", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterNotLike(String value) {
            addCriterion("writer not like", value, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterIn(List<String> values) {
            addCriterion("writer in", values, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterNotIn(List<String> values) {
            addCriterion("writer not in", values, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterBetween(String value1, String value2) {
            addCriterion("writer between", value1, value2, "writer");
            return (Criteria) this;
        }

        public Criteria andWriterNotBetween(String value1, String value2) {
            addCriterion("writer not between", value1, value2, "writer");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andLitpicIsNull() {
            addCriterion("litpic is null");
            return (Criteria) this;
        }

        public Criteria andLitpicIsNotNull() {
            addCriterion("litpic is not null");
            return (Criteria) this;
        }

        public Criteria andLitpicEqualTo(String value) {
            addCriterion("litpic =", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicNotEqualTo(String value) {
            addCriterion("litpic <>", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicGreaterThan(String value) {
            addCriterion("litpic >", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicGreaterThanOrEqualTo(String value) {
            addCriterion("litpic >=", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicLessThan(String value) {
            addCriterion("litpic <", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicLessThanOrEqualTo(String value) {
            addCriterion("litpic <=", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicLike(String value) {
            addCriterion("litpic like", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicNotLike(String value) {
            addCriterion("litpic not like", value, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicIn(List<String> values) {
            addCriterion("litpic in", values, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicNotIn(List<String> values) {
            addCriterion("litpic not in", values, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicBetween(String value1, String value2) {
            addCriterion("litpic between", value1, value2, "litpic");
            return (Criteria) this;
        }

        public Criteria andLitpicNotBetween(String value1, String value2) {
            addCriterion("litpic not between", value1, value2, "litpic");
            return (Criteria) this;
        }

        public Criteria andPubdateIsNull() {
            addCriterion("pubdate is null");
            return (Criteria) this;
        }

        public Criteria andPubdateIsNotNull() {
            addCriterion("pubdate is not null");
            return (Criteria) this;
        }

        public Criteria andPubdateEqualTo(Integer value) {
            addCriterion("pubdate =", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotEqualTo(Integer value) {
            addCriterion("pubdate <>", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateGreaterThan(Integer value) {
            addCriterion("pubdate >", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("pubdate >=", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateLessThan(Integer value) {
            addCriterion("pubdate <", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateLessThanOrEqualTo(Integer value) {
            addCriterion("pubdate <=", value, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateIn(List<Integer> values) {
            addCriterion("pubdate in", values, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotIn(List<Integer> values) {
            addCriterion("pubdate not in", values, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateBetween(Integer value1, Integer value2) {
            addCriterion("pubdate between", value1, value2, "pubdate");
            return (Criteria) this;
        }

        public Criteria andPubdateNotBetween(Integer value1, Integer value2) {
            addCriterion("pubdate not between", value1, value2, "pubdate");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNull() {
            addCriterion("senddate is null");
            return (Criteria) this;
        }

        public Criteria andSenddateIsNotNull() {
            addCriterion("senddate is not null");
            return (Criteria) this;
        }

        public Criteria andSenddateEqualTo(Integer value) {
            addCriterion("senddate =", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotEqualTo(Integer value) {
            addCriterion("senddate <>", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThan(Integer value) {
            addCriterion("senddate >", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateGreaterThanOrEqualTo(Integer value) {
            addCriterion("senddate >=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThan(Integer value) {
            addCriterion("senddate <", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateLessThanOrEqualTo(Integer value) {
            addCriterion("senddate <=", value, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateIn(List<Integer> values) {
            addCriterion("senddate in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotIn(List<Integer> values) {
            addCriterion("senddate not in", values, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateBetween(Integer value1, Integer value2) {
            addCriterion("senddate between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andSenddateNotBetween(Integer value1, Integer value2) {
            addCriterion("senddate not between", value1, value2, "senddate");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andLastpostIsNull() {
            addCriterion("lastpost is null");
            return (Criteria) this;
        }

        public Criteria andLastpostIsNotNull() {
            addCriterion("lastpost is not null");
            return (Criteria) this;
        }

        public Criteria andLastpostEqualTo(Integer value) {
            addCriterion("lastpost =", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostNotEqualTo(Integer value) {
            addCriterion("lastpost <>", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostGreaterThan(Integer value) {
            addCriterion("lastpost >", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastpost >=", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostLessThan(Integer value) {
            addCriterion("lastpost <", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostLessThanOrEqualTo(Integer value) {
            addCriterion("lastpost <=", value, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostIn(List<Integer> values) {
            addCriterion("lastpost in", values, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostNotIn(List<Integer> values) {
            addCriterion("lastpost not in", values, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostBetween(Integer value1, Integer value2) {
            addCriterion("lastpost between", value1, value2, "lastpost");
            return (Criteria) this;
        }

        public Criteria andLastpostNotBetween(Integer value1, Integer value2) {
            addCriterion("lastpost not between", value1, value2, "lastpost");
            return (Criteria) this;
        }

        public Criteria andScoresIsNull() {
            addCriterion("scores is null");
            return (Criteria) this;
        }

        public Criteria andScoresIsNotNull() {
            addCriterion("scores is not null");
            return (Criteria) this;
        }

        public Criteria andScoresEqualTo(Integer value) {
            addCriterion("scores =", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresNotEqualTo(Integer value) {
            addCriterion("scores <>", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresGreaterThan(Integer value) {
            addCriterion("scores >", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresGreaterThanOrEqualTo(Integer value) {
            addCriterion("scores >=", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresLessThan(Integer value) {
            addCriterion("scores <", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresLessThanOrEqualTo(Integer value) {
            addCriterion("scores <=", value, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresIn(List<Integer> values) {
            addCriterion("scores in", values, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresNotIn(List<Integer> values) {
            addCriterion("scores not in", values, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresBetween(Integer value1, Integer value2) {
            addCriterion("scores between", value1, value2, "scores");
            return (Criteria) this;
        }

        public Criteria andScoresNotBetween(Integer value1, Integer value2) {
            addCriterion("scores not between", value1, value2, "scores");
            return (Criteria) this;
        }

        public Criteria andGoodpostIsNull() {
            addCriterion("goodpost is null");
            return (Criteria) this;
        }

        public Criteria andGoodpostIsNotNull() {
            addCriterion("goodpost is not null");
            return (Criteria) this;
        }

        public Criteria andGoodpostEqualTo(Integer value) {
            addCriterion("goodpost =", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostNotEqualTo(Integer value) {
            addCriterion("goodpost <>", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostGreaterThan(Integer value) {
            addCriterion("goodpost >", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodpost >=", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostLessThan(Integer value) {
            addCriterion("goodpost <", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostLessThanOrEqualTo(Integer value) {
            addCriterion("goodpost <=", value, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostIn(List<Integer> values) {
            addCriterion("goodpost in", values, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostNotIn(List<Integer> values) {
            addCriterion("goodpost not in", values, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostBetween(Integer value1, Integer value2) {
            addCriterion("goodpost between", value1, value2, "goodpost");
            return (Criteria) this;
        }

        public Criteria andGoodpostNotBetween(Integer value1, Integer value2) {
            addCriterion("goodpost not between", value1, value2, "goodpost");
            return (Criteria) this;
        }

        public Criteria andBadpostIsNull() {
            addCriterion("badpost is null");
            return (Criteria) this;
        }

        public Criteria andBadpostIsNotNull() {
            addCriterion("badpost is not null");
            return (Criteria) this;
        }

        public Criteria andBadpostEqualTo(Integer value) {
            addCriterion("badpost =", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostNotEqualTo(Integer value) {
            addCriterion("badpost <>", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostGreaterThan(Integer value) {
            addCriterion("badpost >", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostGreaterThanOrEqualTo(Integer value) {
            addCriterion("badpost >=", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostLessThan(Integer value) {
            addCriterion("badpost <", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostLessThanOrEqualTo(Integer value) {
            addCriterion("badpost <=", value, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostIn(List<Integer> values) {
            addCriterion("badpost in", values, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostNotIn(List<Integer> values) {
            addCriterion("badpost not in", values, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostBetween(Integer value1, Integer value2) {
            addCriterion("badpost between", value1, value2, "badpost");
            return (Criteria) this;
        }

        public Criteria andBadpostNotBetween(Integer value1, Integer value2) {
            addCriterion("badpost not between", value1, value2, "badpost");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNull() {
            addCriterion("voteid is null");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNotNull() {
            addCriterion("voteid is not null");
            return (Criteria) this;
        }

        public Criteria andVoteidEqualTo(Integer value) {
            addCriterion("voteid =", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotEqualTo(Integer value) {
            addCriterion("voteid <>", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThan(Integer value) {
            addCriterion("voteid >", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThanOrEqualTo(Integer value) {
            addCriterion("voteid >=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThan(Integer value) {
            addCriterion("voteid <", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThanOrEqualTo(Integer value) {
            addCriterion("voteid <=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidIn(List<Integer> values) {
            addCriterion("voteid in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotIn(List<Integer> values) {
            addCriterion("voteid not in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidBetween(Integer value1, Integer value2) {
            addCriterion("voteid between", value1, value2, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotBetween(Integer value1, Integer value2) {
            addCriterion("voteid not between", value1, value2, "voteid");
            return (Criteria) this;
        }

        public Criteria andNotpostIsNull() {
            addCriterion("notpost is null");
            return (Criteria) this;
        }

        public Criteria andNotpostIsNotNull() {
            addCriterion("notpost is not null");
            return (Criteria) this;
        }

        public Criteria andNotpostEqualTo(Boolean value) {
            addCriterion("notpost =", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostNotEqualTo(Boolean value) {
            addCriterion("notpost <>", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostGreaterThan(Boolean value) {
            addCriterion("notpost >", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostGreaterThanOrEqualTo(Boolean value) {
            addCriterion("notpost >=", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostLessThan(Boolean value) {
            addCriterion("notpost <", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostLessThanOrEqualTo(Boolean value) {
            addCriterion("notpost <=", value, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostIn(List<Boolean> values) {
            addCriterion("notpost in", values, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostNotIn(List<Boolean> values) {
            addCriterion("notpost not in", values, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostBetween(Boolean value1, Boolean value2) {
            addCriterion("notpost between", value1, value2, "notpost");
            return (Criteria) this;
        }

        public Criteria andNotpostNotBetween(Boolean value1, Boolean value2) {
            addCriterion("notpost not between", value1, value2, "notpost");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andDutyadminIsNull() {
            addCriterion("dutyadmin is null");
            return (Criteria) this;
        }

        public Criteria andDutyadminIsNotNull() {
            addCriterion("dutyadmin is not null");
            return (Criteria) this;
        }

        public Criteria andDutyadminEqualTo(Integer value) {
            addCriterion("dutyadmin =", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminNotEqualTo(Integer value) {
            addCriterion("dutyadmin <>", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminGreaterThan(Integer value) {
            addCriterion("dutyadmin >", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminGreaterThanOrEqualTo(Integer value) {
            addCriterion("dutyadmin >=", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminLessThan(Integer value) {
            addCriterion("dutyadmin <", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminLessThanOrEqualTo(Integer value) {
            addCriterion("dutyadmin <=", value, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminIn(List<Integer> values) {
            addCriterion("dutyadmin in", values, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminNotIn(List<Integer> values) {
            addCriterion("dutyadmin not in", values, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminBetween(Integer value1, Integer value2) {
            addCriterion("dutyadmin between", value1, value2, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andDutyadminNotBetween(Integer value1, Integer value2) {
            addCriterion("dutyadmin not between", value1, value2, "dutyadmin");
            return (Criteria) this;
        }

        public Criteria andTackidIsNull() {
            addCriterion("tackid is null");
            return (Criteria) this;
        }

        public Criteria andTackidIsNotNull() {
            addCriterion("tackid is not null");
            return (Criteria) this;
        }

        public Criteria andTackidEqualTo(Integer value) {
            addCriterion("tackid =", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidNotEqualTo(Integer value) {
            addCriterion("tackid <>", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidGreaterThan(Integer value) {
            addCriterion("tackid >", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tackid >=", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidLessThan(Integer value) {
            addCriterion("tackid <", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidLessThanOrEqualTo(Integer value) {
            addCriterion("tackid <=", value, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidIn(List<Integer> values) {
            addCriterion("tackid in", values, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidNotIn(List<Integer> values) {
            addCriterion("tackid not in", values, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidBetween(Integer value1, Integer value2) {
            addCriterion("tackid between", value1, value2, "tackid");
            return (Criteria) this;
        }

        public Criteria andTackidNotBetween(Integer value1, Integer value2) {
            addCriterion("tackid not between", value1, value2, "tackid");
            return (Criteria) this;
        }

        public Criteria andMtypeIsNull() {
            addCriterion("mtype is null");
            return (Criteria) this;
        }

        public Criteria andMtypeIsNotNull() {
            addCriterion("mtype is not null");
            return (Criteria) this;
        }

        public Criteria andMtypeEqualTo(Integer value) {
            addCriterion("mtype =", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeNotEqualTo(Integer value) {
            addCriterion("mtype <>", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeGreaterThan(Integer value) {
            addCriterion("mtype >", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mtype >=", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeLessThan(Integer value) {
            addCriterion("mtype <", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeLessThanOrEqualTo(Integer value) {
            addCriterion("mtype <=", value, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeIn(List<Integer> values) {
            addCriterion("mtype in", values, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeNotIn(List<Integer> values) {
            addCriterion("mtype not in", values, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeBetween(Integer value1, Integer value2) {
            addCriterion("mtype between", value1, value2, "mtype");
            return (Criteria) this;
        }

        public Criteria andMtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("mtype not between", value1, value2, "mtype");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dede_archives
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 14:18:52 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dede_archives
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}