package cn.entity.qdm0020530;

public class DEDE_ARCHIVES {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.id
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.typeid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Short typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.typeid2
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String typeid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.sortrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer sortrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.flag
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.ismake
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Short ismake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.channel
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Short channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.arcrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Short arcrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.click
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer click;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.money
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Short money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.title
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.shorttitle
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String shorttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.color
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.writer
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String writer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.source
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.litpic
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String litpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.pubdate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer pubdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.senddate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer senddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.mid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.keywords
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.lastpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer lastpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.scores
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer scores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.goodpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer goodpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.badpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer badpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.voteid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.notpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Boolean notpost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.description
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.filename
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.dutyadmin
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer dutyadmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.tackid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer tackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.mtype
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer mtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_archives.weight
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.id
     *
     * @return the value of dede_archives.id
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.id
     *
     * @param id the value for dede_archives.id
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.typeid
     *
     * @return the value of dede_archives.typeid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Short getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.typeid
     *
     * @param typeid the value for dede_archives.typeid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setTypeid(Short typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.typeid2
     *
     * @return the value of dede_archives.typeid2
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getTypeid2() {
        return typeid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.typeid2
     *
     * @param typeid2 the value for dede_archives.typeid2
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setTypeid2(String typeid2) {
        this.typeid2 = typeid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.sortrank
     *
     * @return the value of dede_archives.sortrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getSortrank() {
        return sortrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.sortrank
     *
     * @param sortrank the value for dede_archives.sortrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setSortrank(Integer sortrank) {
        this.sortrank = sortrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.flag
     *
     * @return the value of dede_archives.flag
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.flag
     *
     * @param flag the value for dede_archives.flag
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.ismake
     *
     * @return the value of dede_archives.ismake
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Short getIsmake() {
        return ismake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.ismake
     *
     * @param ismake the value for dede_archives.ismake
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setIsmake(Short ismake) {
        this.ismake = ismake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.channel
     *
     * @return the value of dede_archives.channel
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Short getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.channel
     *
     * @param channel the value for dede_archives.channel
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setChannel(Short channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.arcrank
     *
     * @return the value of dede_archives.arcrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Short getArcrank() {
        return arcrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.arcrank
     *
     * @param arcrank the value for dede_archives.arcrank
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setArcrank(Short arcrank) {
        this.arcrank = arcrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.click
     *
     * @return the value of dede_archives.click
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.click
     *
     * @param click the value for dede_archives.click
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.money
     *
     * @return the value of dede_archives.money
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Short getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.money
     *
     * @param money the value for dede_archives.money
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setMoney(Short money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.title
     *
     * @return the value of dede_archives.title
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.title
     *
     * @param title the value for dede_archives.title
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.shorttitle
     *
     * @return the value of dede_archives.shorttitle
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getShorttitle() {
        return shorttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.shorttitle
     *
     * @param shorttitle the value for dede_archives.shorttitle
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setShorttitle(String shorttitle) {
        this.shorttitle = shorttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.color
     *
     * @return the value of dede_archives.color
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.color
     *
     * @param color the value for dede_archives.color
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.writer
     *
     * @return the value of dede_archives.writer
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.writer
     *
     * @param writer the value for dede_archives.writer
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setWriter(String writer) {
        this.writer = writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.source
     *
     * @return the value of dede_archives.source
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.source
     *
     * @param source the value for dede_archives.source
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.litpic
     *
     * @return the value of dede_archives.litpic
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getLitpic() {
        return litpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.litpic
     *
     * @param litpic the value for dede_archives.litpic
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setLitpic(String litpic) {
        this.litpic = litpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.pubdate
     *
     * @return the value of dede_archives.pubdate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getPubdate() {
        return pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.pubdate
     *
     * @param pubdate the value for dede_archives.pubdate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setPubdate(Integer pubdate) {
        this.pubdate = pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.senddate
     *
     * @return the value of dede_archives.senddate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getSenddate() {
        return senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.senddate
     *
     * @param senddate the value for dede_archives.senddate
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setSenddate(Integer senddate) {
        this.senddate = senddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.mid
     *
     * @return the value of dede_archives.mid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.mid
     *
     * @param mid the value for dede_archives.mid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.keywords
     *
     * @return the value of dede_archives.keywords
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.keywords
     *
     * @param keywords the value for dede_archives.keywords
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.lastpost
     *
     * @return the value of dede_archives.lastpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getLastpost() {
        return lastpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.lastpost
     *
     * @param lastpost the value for dede_archives.lastpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setLastpost(Integer lastpost) {
        this.lastpost = lastpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.scores
     *
     * @return the value of dede_archives.scores
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.scores
     *
     * @param scores the value for dede_archives.scores
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setScores(Integer scores) {
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.goodpost
     *
     * @return the value of dede_archives.goodpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getGoodpost() {
        return goodpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.goodpost
     *
     * @param goodpost the value for dede_archives.goodpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setGoodpost(Integer goodpost) {
        this.goodpost = goodpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.badpost
     *
     * @return the value of dede_archives.badpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getBadpost() {
        return badpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.badpost
     *
     * @param badpost the value for dede_archives.badpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setBadpost(Integer badpost) {
        this.badpost = badpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.voteid
     *
     * @return the value of dede_archives.voteid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.voteid
     *
     * @param voteid the value for dede_archives.voteid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.notpost
     *
     * @return the value of dede_archives.notpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Boolean getNotpost() {
        return notpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.notpost
     *
     * @param notpost the value for dede_archives.notpost
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setNotpost(Boolean notpost) {
        this.notpost = notpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.description
     *
     * @return the value of dede_archives.description
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.description
     *
     * @param description the value for dede_archives.description
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.filename
     *
     * @return the value of dede_archives.filename
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.filename
     *
     * @param filename the value for dede_archives.filename
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.dutyadmin
     *
     * @return the value of dede_archives.dutyadmin
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getDutyadmin() {
        return dutyadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.dutyadmin
     *
     * @param dutyadmin the value for dede_archives.dutyadmin
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setDutyadmin(Integer dutyadmin) {
        this.dutyadmin = dutyadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.tackid
     *
     * @return the value of dede_archives.tackid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getTackid() {
        return tackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.tackid
     *
     * @param tackid the value for dede_archives.tackid
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setTackid(Integer tackid) {
        this.tackid = tackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.mtype
     *
     * @return the value of dede_archives.mtype
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.mtype
     *
     * @param mtype the value for dede_archives.mtype
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setMtype(Integer mtype) {
        this.mtype = mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_archives.weight
     *
     * @return the value of dede_archives.weight
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_archives.weight
     *
     * @param weight the value for dede_archives.weight
     *
     * @mbggenerated Wed Sep 07 14:18:52 CST 2016
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}