package cn.xidu.app.entity;

import java.util.Date;

public class APP_USER {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.ID
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.NAME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.PWD
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.MOB
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private String mob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.LOGIN_TIME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.CREATE_DATE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_info.SOURCE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.ID
     *
     * @return the value of app_user_info.ID
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.ID
     *
     * @param id the value for app_user_info.ID
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.NAME
     *
     * @return the value of app_user_info.NAME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.NAME
     *
     * @param name the value for app_user_info.NAME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.PWD
     *
     * @return the value of app_user_info.PWD
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.PWD
     *
     * @param pwd the value for app_user_info.PWD
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.MOB
     *
     * @return the value of app_user_info.MOB
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public String getMob() {
        return mob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.MOB
     *
     * @param mob the value for app_user_info.MOB
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setMob(String mob) {
        this.mob = mob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.LOGIN_TIME
     *
     * @return the value of app_user_info.LOGIN_TIME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.LOGIN_TIME
     *
     * @param loginTime the value for app_user_info.LOGIN_TIME
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.CREATE_DATE
     *
     * @return the value of app_user_info.CREATE_DATE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.CREATE_DATE
     *
     * @param createDate the value for app_user_info.CREATE_DATE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_info.SOURCE
     *
     * @return the value of app_user_info.SOURCE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_info.SOURCE
     *
     * @param source the value for app_user_info.SOURCE
     *
     * @mbggenerated Wed Sep 14 10:50:09 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }
}