package cn.entity.local;

import java.util.ArrayList;
import java.util.List;

public class CRM_Entity2Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public CRM_Entity2Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMobIsNull() {
            addCriterion("mob is null");
            return (Criteria) this;
        }

        public Criteria andMobIsNotNull() {
            addCriterion("mob is not null");
            return (Criteria) this;
        }

        public Criteria andMobEqualTo(String value) {
            addCriterion("mob =", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobNotEqualTo(String value) {
            addCriterion("mob <>", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobGreaterThan(String value) {
            addCriterion("mob >", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobGreaterThanOrEqualTo(String value) {
            addCriterion("mob >=", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobLessThan(String value) {
            addCriterion("mob <", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobLessThanOrEqualTo(String value) {
            addCriterion("mob <=", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobLike(String value) {
            addCriterion("mob like", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobNotLike(String value) {
            addCriterion("mob not like", value, "mob");
            return (Criteria) this;
        }

        public Criteria andMobIn(List<String> values) {
            addCriterion("mob in", values, "mob");
            return (Criteria) this;
        }

        public Criteria andMobNotIn(List<String> values) {
            addCriterion("mob not in", values, "mob");
            return (Criteria) this;
        }

        public Criteria andMobBetween(String value1, String value2) {
            addCriterion("mob between", value1, value2, "mob");
            return (Criteria) this;
        }

        public Criteria andMobNotBetween(String value1, String value2) {
            addCriterion("mob not between", value1, value2, "mob");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(String value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(String value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(String value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(String value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(String value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(String value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLike(String value) {
            addCriterion("date like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotLike(String value) {
            addCriterion("date not like", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<String> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<String> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(String value1, String value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(String value1, String value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andLurlIsNull() {
            addCriterion("lurl is null");
            return (Criteria) this;
        }

        public Criteria andLurlIsNotNull() {
            addCriterion("lurl is not null");
            return (Criteria) this;
        }

        public Criteria andLurlEqualTo(String value) {
            addCriterion("lurl =", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotEqualTo(String value) {
            addCriterion("lurl <>", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlGreaterThan(String value) {
            addCriterion("lurl >", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlGreaterThanOrEqualTo(String value) {
            addCriterion("lurl >=", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLessThan(String value) {
            addCriterion("lurl <", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLessThanOrEqualTo(String value) {
            addCriterion("lurl <=", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlLike(String value) {
            addCriterion("lurl like", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotLike(String value) {
            addCriterion("lurl not like", value, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlIn(List<String> values) {
            addCriterion("lurl in", values, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotIn(List<String> values) {
            addCriterion("lurl not in", values, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlBetween(String value1, String value2) {
            addCriterion("lurl between", value1, value2, "lurl");
            return (Criteria) this;
        }

        public Criteria andLurlNotBetween(String value1, String value2) {
            addCriterion("lurl not between", value1, value2, "lurl");
            return (Criteria) this;
        }

        public Criteria andRurlIsNull() {
            addCriterion("rurl is null");
            return (Criteria) this;
        }

        public Criteria andRurlIsNotNull() {
            addCriterion("rurl is not null");
            return (Criteria) this;
        }

        public Criteria andRurlEqualTo(String value) {
            addCriterion("rurl =", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlNotEqualTo(String value) {
            addCriterion("rurl <>", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlGreaterThan(String value) {
            addCriterion("rurl >", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlGreaterThanOrEqualTo(String value) {
            addCriterion("rurl >=", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlLessThan(String value) {
            addCriterion("rurl <", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlLessThanOrEqualTo(String value) {
            addCriterion("rurl <=", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlLike(String value) {
            addCriterion("rurl like", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlNotLike(String value) {
            addCriterion("rurl not like", value, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlIn(List<String> values) {
            addCriterion("rurl in", values, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlNotIn(List<String> values) {
            addCriterion("rurl not in", values, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlBetween(String value1, String value2) {
            addCriterion("rurl between", value1, value2, "rurl");
            return (Criteria) this;
        }

        public Criteria andRurlNotBetween(String value1, String value2) {
            addCriterion("rurl not between", value1, value2, "rurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newcrm
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 06 18:56:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}