package cn.entity.local;

public class CRM_Entity2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.id
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.name
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.mob
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String mob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.source
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.date
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.code
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.lurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String lurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newcrm.rurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    private String rurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.id
     *
     * @return the value of newcrm.id
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.id
     *
     * @param id the value for newcrm.id
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.name
     *
     * @return the value of newcrm.name
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.name
     *
     * @param name the value for newcrm.name
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.mob
     *
     * @return the value of newcrm.mob
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getMob() {
        return mob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.mob
     *
     * @param mob the value for newcrm.mob
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setMob(String mob) {
        this.mob = mob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.source
     *
     * @return the value of newcrm.source
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.source
     *
     * @param source the value for newcrm.source
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.date
     *
     * @return the value of newcrm.date
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.date
     *
     * @param date the value for newcrm.date
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.code
     *
     * @return the value of newcrm.code
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.code
     *
     * @param code the value for newcrm.code
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.lurl
     *
     * @return the value of newcrm.lurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getLurl() {
        return lurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.lurl
     *
     * @param lurl the value for newcrm.lurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setLurl(String lurl) {
        this.lurl = lurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newcrm.rurl
     *
     * @return the value of newcrm.rurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public String getRurl() {
        return rurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newcrm.rurl
     *
     * @param rurl the value for newcrm.rurl
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    public void setRurl(String rurl) {
        this.rurl = rurl;
    }
}