package cn.dao.newzhibo;

import cn.entity.newzhibo.NEWZhibo_CustomerType;
import cn.entity.newzhibo.NEWZhibo_CustomerTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NEWZhibo_CustomerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int countByExample(NEWZhibo_CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int deleteByExample(NEWZhibo_CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int insert(NEWZhibo_CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int insertSelective(NEWZhibo_CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    List<NEWZhibo_CustomerType> selectByExample(NEWZhibo_CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    NEWZhibo_CustomerType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int updateByExampleSelective(@Param("record") NEWZhibo_CustomerType record, @Param("example") NEWZhibo_CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int updateByExample(@Param("record") NEWZhibo_CustomerType record, @Param("example") NEWZhibo_CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int updateByPrimaryKeySelective(NEWZhibo_CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer_type
     *
     * @mbggenerated Mon Sep 26 15:03:57 CST 2016
     */
    int updateByPrimaryKey(NEWZhibo_CustomerType record);
}