package cn.dao.xdchats;

import cn.entity.xdchats.OPENDOOR;
import cn.entity.xdchats.OPENDOORExample;
import cn.entity.xdchats.OPENDOORWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OPENDOORMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int countByExample(OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int deleteByExample(OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int insert(OPENDOORWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int insertSelective(OPENDOORWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    List<OPENDOORWithBLOBs> selectByExampleWithBLOBs(OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    List<OPENDOOR> selectByExample(OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    OPENDOORWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") OPENDOORWithBLOBs record, @Param("example") OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OPENDOORWithBLOBs record, @Param("example") OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExample(@Param("record") OPENDOOR record, @Param("example") OPENDOORExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKeySelective(OPENDOORWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OPENDOORWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opendoor
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKey(OPENDOOR record);
}