package cn.dao.xdchats;

import cn.entity.xdchats.XD_Customer;
import cn.entity.xdchats.XD_CustomerExample;
import cn.entity.xdchats.XD_CustomerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XD_CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int countByExample(XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int deleteByExample(XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int insert(XD_CustomerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int insertSelective(XD_CustomerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    List<XD_CustomerWithBLOBs> selectByExampleWithBLOBs(XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    List<XD_Customer> selectByExample(XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    XD_CustomerWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") XD_CustomerWithBLOBs record, @Param("example") XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") XD_CustomerWithBLOBs record, @Param("example") XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByExample(@Param("record") XD_Customer record, @Param("example") XD_CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKeySelective(XD_CustomerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(XD_CustomerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_customer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    int updateByPrimaryKey(XD_Customer record);
}