package cn.dao.local;

import cn.entity.local.CRM_Entity;
import cn.entity.local.CRM_EntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CRM_EntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int countByExample(CRM_EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int deleteByExample(CRM_EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int insert(CRM_Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int insertSelective(CRM_Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    List<CRM_Entity> selectByExample(CRM_EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") CRM_Entity record, @Param("example") CRM_EntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crm
     *
     * @mbggenerated Wed Nov 23 17:24:43 CST 2016
     */
    int updateByExample(@Param("record") CRM_Entity record, @Param("example") CRM_EntityExample example);
}