package cn.dao.local;

import cn.entity.local.CRM_Entity2;
import cn.entity.local.CRM_Entity2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CRM_Entity2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int countByExample(CRM_Entity2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int deleteByExample(CRM_Entity2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int insert(CRM_Entity2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int insertSelective(CRM_Entity2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    List<CRM_Entity2> selectByExample(CRM_Entity2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    CRM_Entity2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") CRM_Entity2 record, @Param("example") CRM_Entity2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int updateByExample(@Param("record") CRM_Entity2 record, @Param("example") CRM_Entity2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int updateByPrimaryKeySelective(CRM_Entity2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newcrm
     *
     * @mbggenerated Tue Dec 06 18:56:54 CST 2016
     */
    int updateByPrimaryKey(CRM_Entity2 record);
}