package cn.entity.xdchats;

import java.util.Date;

public class XD_Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.id
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.CREATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.CREATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.userName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.nickName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.pwd
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.sex
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.mobile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.qq
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.ip
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.lastLoginTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.usedVideoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long usedvideotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.videoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long videotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.isChat
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String ischat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.chatTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long chattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.userId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.url
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.faceImg
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String faceimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.typeId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private Long typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.status
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.mail
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.business
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.openAccount
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String openaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.accountPrice
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String accountprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.realName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.profile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String profile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.referer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.linksource
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String linksource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_customer.roomNo
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    private String roomno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.id
     *
     * @return the value of xd_customer.id
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.id
     *
     * @param id the value for xd_customer.id
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.DELETE_FLAG
     *
     * @return the value of xd_customer.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.DELETE_FLAG
     *
     * @param deleteFlag the value for xd_customer.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.CREATE_BY
     *
     * @return the value of xd_customer.CREATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.CREATE_BY
     *
     * @param createBy the value for xd_customer.CREATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.CREATE_DATE
     *
     * @return the value of xd_customer.CREATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.CREATE_DATE
     *
     * @param createDate the value for xd_customer.CREATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.LAST_UPDATE_BY
     *
     * @return the value of xd_customer.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for xd_customer.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setLastUpdateBy(Long lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.LAST_UPDATE_DATE
     *
     * @return the value of xd_customer.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for xd_customer.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.userName
     *
     * @return the value of xd_customer.userName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.userName
     *
     * @param username the value for xd_customer.userName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.nickName
     *
     * @return the value of xd_customer.nickName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.nickName
     *
     * @param nickname the value for xd_customer.nickName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.pwd
     *
     * @return the value of xd_customer.pwd
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.pwd
     *
     * @param pwd the value for xd_customer.pwd
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.sex
     *
     * @return the value of xd_customer.sex
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.sex
     *
     * @param sex the value for xd_customer.sex
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.mobile
     *
     * @return the value of xd_customer.mobile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.mobile
     *
     * @param mobile the value for xd_customer.mobile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.qq
     *
     * @return the value of xd_customer.qq
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.qq
     *
     * @param qq the value for xd_customer.qq
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.ip
     *
     * @return the value of xd_customer.ip
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.ip
     *
     * @param ip the value for xd_customer.ip
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.lastLoginTime
     *
     * @return the value of xd_customer.lastLoginTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.lastLoginTime
     *
     * @param lastlogintime the value for xd_customer.lastLoginTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.usedVideoTime
     *
     * @return the value of xd_customer.usedVideoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getUsedvideotime() {
        return usedvideotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.usedVideoTime
     *
     * @param usedvideotime the value for xd_customer.usedVideoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setUsedvideotime(Long usedvideotime) {
        this.usedvideotime = usedvideotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.videoTime
     *
     * @return the value of xd_customer.videoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getVideotime() {
        return videotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.videoTime
     *
     * @param videotime the value for xd_customer.videoTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setVideotime(Long videotime) {
        this.videotime = videotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.isChat
     *
     * @return the value of xd_customer.isChat
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getIschat() {
        return ischat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.isChat
     *
     * @param ischat the value for xd_customer.isChat
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setIschat(String ischat) {
        this.ischat = ischat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.chatTime
     *
     * @return the value of xd_customer.chatTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getChattime() {
        return chattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.chatTime
     *
     * @param chattime the value for xd_customer.chatTime
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setChattime(Long chattime) {
        this.chattime = chattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.userId
     *
     * @return the value of xd_customer.userId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.userId
     *
     * @param userid the value for xd_customer.userId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.url
     *
     * @return the value of xd_customer.url
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.url
     *
     * @param url the value for xd_customer.url
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.faceImg
     *
     * @return the value of xd_customer.faceImg
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getFaceimg() {
        return faceimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.faceImg
     *
     * @param faceimg the value for xd_customer.faceImg
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setFaceimg(String faceimg) {
        this.faceimg = faceimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.typeId
     *
     * @return the value of xd_customer.typeId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.typeId
     *
     * @param typeid the value for xd_customer.typeId
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.status
     *
     * @return the value of xd_customer.status
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.status
     *
     * @param status the value for xd_customer.status
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.mail
     *
     * @return the value of xd_customer.mail
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.mail
     *
     * @param mail the value for xd_customer.mail
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.business
     *
     * @return the value of xd_customer.business
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.business
     *
     * @param business the value for xd_customer.business
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.openAccount
     *
     * @return the value of xd_customer.openAccount
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getOpenaccount() {
        return openaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.openAccount
     *
     * @param openaccount the value for xd_customer.openAccount
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setOpenaccount(String openaccount) {
        this.openaccount = openaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.accountPrice
     *
     * @return the value of xd_customer.accountPrice
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getAccountprice() {
        return accountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.accountPrice
     *
     * @param accountprice the value for xd_customer.accountPrice
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setAccountprice(String accountprice) {
        this.accountprice = accountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.realName
     *
     * @return the value of xd_customer.realName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.realName
     *
     * @param realname the value for xd_customer.realName
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.profile
     *
     * @return the value of xd_customer.profile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.profile
     *
     * @param profile the value for xd_customer.profile
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.referer
     *
     * @return the value of xd_customer.referer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.referer
     *
     * @param referer the value for xd_customer.referer
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setReferer(String referer) {
        this.referer = referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.linksource
     *
     * @return the value of xd_customer.linksource
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getLinksource() {
        return linksource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.linksource
     *
     * @param linksource the value for xd_customer.linksource
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setLinksource(String linksource) {
        this.linksource = linksource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_customer.roomNo
     *
     * @return the value of xd_customer.roomNo
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_customer.roomNo
     *
     * @param roomno the value for xd_customer.roomNo
     *
     * @mbggenerated Mon Sep 05 15:26:44 CST 2016
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }
}