package cn.entity.xdchats;

import java.util.Date;

public class ZXDY {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.id
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.CREATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Long createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.CREATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Long lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.qt
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private String qt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.qi
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Long qi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.qn
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private String qn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.at
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private String at;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.ai
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Long ai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.an
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private String an;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xd_zxdy.status
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.id
     *
     * @return the value of xd_zxdy.id
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.id
     *
     * @param id the value for xd_zxdy.id
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.CREATE_BY
     *
     * @return the value of xd_zxdy.CREATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.CREATE_BY
     *
     * @param createBy the value for xd_zxdy.CREATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.CREATE_DATE
     *
     * @return the value of xd_zxdy.CREATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.CREATE_DATE
     *
     * @param createDate the value for xd_zxdy.CREATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.LAST_UPDATE_BY
     *
     * @return the value of xd_zxdy.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Long getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.LAST_UPDATE_BY
     *
     * @param lastUpdateBy the value for xd_zxdy.LAST_UPDATE_BY
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setLastUpdateBy(Long lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.LAST_UPDATE_DATE
     *
     * @return the value of xd_zxdy.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for xd_zxdy.LAST_UPDATE_DATE
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.DELETE_FLAG
     *
     * @return the value of xd_zxdy.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.DELETE_FLAG
     *
     * @param deleteFlag the value for xd_zxdy.DELETE_FLAG
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.qt
     *
     * @return the value of xd_zxdy.qt
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.qt
     *
     * @param qt the value for xd_zxdy.qt
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setQt(String qt) {
        this.qt = qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.qi
     *
     * @return the value of xd_zxdy.qi
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Long getQi() {
        return qi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.qi
     *
     * @param qi the value for xd_zxdy.qi
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setQi(Long qi) {
        this.qi = qi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.qn
     *
     * @return the value of xd_zxdy.qn
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public String getQn() {
        return qn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.qn
     *
     * @param qn the value for xd_zxdy.qn
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setQn(String qn) {
        this.qn = qn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.at
     *
     * @return the value of xd_zxdy.at
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public String getAt() {
        return at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.at
     *
     * @param at the value for xd_zxdy.at
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setAt(String at) {
        this.at = at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.ai
     *
     * @return the value of xd_zxdy.ai
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Long getAi() {
        return ai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.ai
     *
     * @param ai the value for xd_zxdy.ai
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setAi(Long ai) {
        this.ai = ai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.an
     *
     * @return the value of xd_zxdy.an
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public String getAn() {
        return an;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.an
     *
     * @param an the value for xd_zxdy.an
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setAn(String an) {
        this.an = an;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xd_zxdy.status
     *
     * @return the value of xd_zxdy.status
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xd_zxdy.status
     *
     * @param status the value for xd_zxdy.status
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}