package cn.entity.xdchats;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZXDYExample {
	protected Integer offset;
	protected Integer size; 
	
	public Integer getOffset() {
		return offset;
	}

	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public ZXDYExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Long value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Long value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Long value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Long value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Long> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Long> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Long value1, Long value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNull() {
            addCriterion("LAST_UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIsNotNull() {
            addCriterion("LAST_UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByEqualTo(Long value) {
            addCriterion("LAST_UPDATE_BY =", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotEqualTo(Long value) {
            addCriterion("LAST_UPDATE_BY <>", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThan(Long value) {
            addCriterion("LAST_UPDATE_BY >", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATE_BY >=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThan(Long value) {
            addCriterion("LAST_UPDATE_BY <", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByLessThanOrEqualTo(Long value) {
            addCriterion("LAST_UPDATE_BY <=", value, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByIn(List<Long> values) {
            addCriterion("LAST_UPDATE_BY in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotIn(List<Long> values) {
            addCriterion("LAST_UPDATE_BY not in", values, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATE_BY between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateByNotBetween(Long value1, Long value2) {
            addCriterion("LAST_UPDATE_BY not between", value1, value2, "lastUpdateBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andQtIsNull() {
            addCriterion("qt is null");
            return (Criteria) this;
        }

        public Criteria andQtIsNotNull() {
            addCriterion("qt is not null");
            return (Criteria) this;
        }

        public Criteria andQtEqualTo(String value) {
            addCriterion("qt =", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotEqualTo(String value) {
            addCriterion("qt <>", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtGreaterThan(String value) {
            addCriterion("qt >", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtGreaterThanOrEqualTo(String value) {
            addCriterion("qt >=", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtLessThan(String value) {
            addCriterion("qt <", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtLessThanOrEqualTo(String value) {
            addCriterion("qt <=", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtLike(String value) {
            addCriterion("qt like", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotLike(String value) {
            addCriterion("qt not like", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtIn(List<String> values) {
            addCriterion("qt in", values, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotIn(List<String> values) {
            addCriterion("qt not in", values, "qt");
            return (Criteria) this;
        }

        public Criteria andQtBetween(String value1, String value2) {
            addCriterion("qt between", value1, value2, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotBetween(String value1, String value2) {
            addCriterion("qt not between", value1, value2, "qt");
            return (Criteria) this;
        }

        public Criteria andQiIsNull() {
            addCriterion("qi is null");
            return (Criteria) this;
        }

        public Criteria andQiIsNotNull() {
            addCriterion("qi is not null");
            return (Criteria) this;
        }

        public Criteria andQiEqualTo(Long value) {
            addCriterion("qi =", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiNotEqualTo(Long value) {
            addCriterion("qi <>", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiGreaterThan(Long value) {
            addCriterion("qi >", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiGreaterThanOrEqualTo(Long value) {
            addCriterion("qi >=", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiLessThan(Long value) {
            addCriterion("qi <", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiLessThanOrEqualTo(Long value) {
            addCriterion("qi <=", value, "qi");
            return (Criteria) this;
        }

        public Criteria andQiIn(List<Long> values) {
            addCriterion("qi in", values, "qi");
            return (Criteria) this;
        }

        public Criteria andQiNotIn(List<Long> values) {
            addCriterion("qi not in", values, "qi");
            return (Criteria) this;
        }

        public Criteria andQiBetween(Long value1, Long value2) {
            addCriterion("qi between", value1, value2, "qi");
            return (Criteria) this;
        }

        public Criteria andQiNotBetween(Long value1, Long value2) {
            addCriterion("qi not between", value1, value2, "qi");
            return (Criteria) this;
        }

        public Criteria andQnIsNull() {
            addCriterion("qn is null");
            return (Criteria) this;
        }

        public Criteria andQnIsNotNull() {
            addCriterion("qn is not null");
            return (Criteria) this;
        }

        public Criteria andQnEqualTo(String value) {
            addCriterion("qn =", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnNotEqualTo(String value) {
            addCriterion("qn <>", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnGreaterThan(String value) {
            addCriterion("qn >", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnGreaterThanOrEqualTo(String value) {
            addCriterion("qn >=", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnLessThan(String value) {
            addCriterion("qn <", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnLessThanOrEqualTo(String value) {
            addCriterion("qn <=", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnLike(String value) {
            addCriterion("qn like", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnNotLike(String value) {
            addCriterion("qn not like", value, "qn");
            return (Criteria) this;
        }

        public Criteria andQnIn(List<String> values) {
            addCriterion("qn in", values, "qn");
            return (Criteria) this;
        }

        public Criteria andQnNotIn(List<String> values) {
            addCriterion("qn not in", values, "qn");
            return (Criteria) this;
        }

        public Criteria andQnBetween(String value1, String value2) {
            addCriterion("qn between", value1, value2, "qn");
            return (Criteria) this;
        }

        public Criteria andQnNotBetween(String value1, String value2) {
            addCriterion("qn not between", value1, value2, "qn");
            return (Criteria) this;
        }

        public Criteria andAtIsNull() {
            addCriterion("at is null");
            return (Criteria) this;
        }

        public Criteria andAtIsNotNull() {
            addCriterion("at is not null");
            return (Criteria) this;
        }

        public Criteria andAtEqualTo(String value) {
            addCriterion("at =", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtNotEqualTo(String value) {
            addCriterion("at <>", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtGreaterThan(String value) {
            addCriterion("at >", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtGreaterThanOrEqualTo(String value) {
            addCriterion("at >=", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtLessThan(String value) {
            addCriterion("at <", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtLessThanOrEqualTo(String value) {
            addCriterion("at <=", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtLike(String value) {
            addCriterion("at like", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtNotLike(String value) {
            addCriterion("at not like", value, "at");
            return (Criteria) this;
        }

        public Criteria andAtIn(List<String> values) {
            addCriterion("at in", values, "at");
            return (Criteria) this;
        }

        public Criteria andAtNotIn(List<String> values) {
            addCriterion("at not in", values, "at");
            return (Criteria) this;
        }

        public Criteria andAtBetween(String value1, String value2) {
            addCriterion("at between", value1, value2, "at");
            return (Criteria) this;
        }

        public Criteria andAtNotBetween(String value1, String value2) {
            addCriterion("at not between", value1, value2, "at");
            return (Criteria) this;
        }

        public Criteria andAiIsNull() {
            addCriterion("ai is null");
            return (Criteria) this;
        }

        public Criteria andAiIsNotNull() {
            addCriterion("ai is not null");
            return (Criteria) this;
        }

        public Criteria andAiEqualTo(Long value) {
            addCriterion("ai =", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiNotEqualTo(Long value) {
            addCriterion("ai <>", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiGreaterThan(Long value) {
            addCriterion("ai >", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiGreaterThanOrEqualTo(Long value) {
            addCriterion("ai >=", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiLessThan(Long value) {
            addCriterion("ai <", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiLessThanOrEqualTo(Long value) {
            addCriterion("ai <=", value, "ai");
            return (Criteria) this;
        }

        public Criteria andAiIn(List<Long> values) {
            addCriterion("ai in", values, "ai");
            return (Criteria) this;
        }

        public Criteria andAiNotIn(List<Long> values) {
            addCriterion("ai not in", values, "ai");
            return (Criteria) this;
        }

        public Criteria andAiBetween(Long value1, Long value2) {
            addCriterion("ai between", value1, value2, "ai");
            return (Criteria) this;
        }

        public Criteria andAiNotBetween(Long value1, Long value2) {
            addCriterion("ai not between", value1, value2, "ai");
            return (Criteria) this;
        }

        public Criteria andAnIsNull() {
            addCriterion("an is null");
            return (Criteria) this;
        }

        public Criteria andAnIsNotNull() {
            addCriterion("an is not null");
            return (Criteria) this;
        }

        public Criteria andAnEqualTo(String value) {
            addCriterion("an =", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnNotEqualTo(String value) {
            addCriterion("an <>", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnGreaterThan(String value) {
            addCriterion("an >", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnGreaterThanOrEqualTo(String value) {
            addCriterion("an >=", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnLessThan(String value) {
            addCriterion("an <", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnLessThanOrEqualTo(String value) {
            addCriterion("an <=", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnLike(String value) {
            addCriterion("an like", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnNotLike(String value) {
            addCriterion("an not like", value, "an");
            return (Criteria) this;
        }

        public Criteria andAnIn(List<String> values) {
            addCriterion("an in", values, "an");
            return (Criteria) this;
        }

        public Criteria andAnNotIn(List<String> values) {
            addCriterion("an not in", values, "an");
            return (Criteria) this;
        }

        public Criteria andAnBetween(String value1, String value2) {
            addCriterion("an between", value1, value2, "an");
            return (Criteria) this;
        }

        public Criteria andAnNotBetween(String value1, String value2) {
            addCriterion("an not between", value1, value2, "an");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xd_zxdy
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 12 14:54:57 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xd_zxdy
     *
     * @mbggenerated Mon Sep 12 14:54:57 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}