package cn.dao.guanwang;

import cn.entity.guanwang.GW_DEDE_MEMBER;
import cn.entity.guanwang.GW_DEDE_MEMBERExample;
import cn.entity.guanwang.GW_DEDE_MEMBERKey;
import cn.entity.guanwang.GW_DEDE_MEMBERWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/** 
* @ClassName: GW_DEDE_MEMBERMapper 
* @Description:
* @author ZHANGCHENG
* @date 2016-9-2 下午2:06:18 
*  
*/ 
public interface GW_DEDE_MEMBERMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int countByExample(GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int deleteByExample(GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int deleteByPrimaryKey(GW_DEDE_MEMBERKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int insert(GW_DEDE_MEMBERWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int insertSelective(GW_DEDE_MEMBERWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    List<GW_DEDE_MEMBERWithBLOBs> selectByExampleWithBLOBs(GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    List<GW_DEDE_MEMBER> selectByExample(GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    GW_DEDE_MEMBERWithBLOBs selectByPrimaryKey(GW_DEDE_MEMBERKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByExampleSelective(@Param("record") GW_DEDE_MEMBERWithBLOBs record, @Param("example") GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") GW_DEDE_MEMBERWithBLOBs record, @Param("example") GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByExample(@Param("record") GW_DEDE_MEMBER record, @Param("example") GW_DEDE_MEMBERExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByPrimaryKeySelective(GW_DEDE_MEMBERWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(GW_DEDE_MEMBERWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dede_member
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    int updateByPrimaryKey(GW_DEDE_MEMBER record);
}