package cn.dao.guanwang;

import cn.entity.guanwang.GW_XiduWeb;
import cn.entity.guanwang.GW_XiduWebExample;
import cn.entity.guanwang.GW_XiduWebKey;
import cn.entity.guanwang.GW_XiduWebWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GW_XiduWebMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int countByExample(GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int deleteByExample(GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int deleteByPrimaryKey(GW_XiduWebKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int insert(GW_XiduWebWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int insertSelective(GW_XiduWebWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    List<GW_XiduWebWithBLOBs> selectByExampleWithBLOBs(GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    List<GW_XiduWeb> selectByExample(GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    GW_XiduWebWithBLOBs selectByPrimaryKey(GW_XiduWebKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") GW_XiduWebWithBLOBs record, @Param("example") GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") GW_XiduWebWithBLOBs record, @Param("example") GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByExample(@Param("record") GW_XiduWeb record, @Param("example") GW_XiduWebExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByPrimaryKeySelective(GW_XiduWebWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(GW_XiduWebWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guanwang_xiduweb
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    int updateByPrimaryKey(GW_XiduWeb record);
}