package cn.entity.guanwang;

/** 
* @ClassName: GW_DEDE_MEMBERKey 
* @Description: 
* @author ZHANGCHENG
* @date 2016-9-2 下午2:08:37 
*  
*/ 
public class GW_DEDE_MEMBERKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_member.mid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dede_member.userid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_member.mid
     *
     * @return the value of dede_member.mid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_member.mid
     *
     * @param mid the value for dede_member.mid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dede_member.userid
     *
     * @return the value of dede_member.userid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dede_member.userid
     *
     * @param userid the value for dede_member.userid
     *
     * @mbggenerated Tue Aug 30 17:23:22 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}