package cn.entity.guanwang;

public class GW_XiduWeb extends GW_XiduWebKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.mtype
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String mtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.pwd
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.uname
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.sex
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.rank
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.uptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.exptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short exptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.money
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.email
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.scores
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer scores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.matt
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short matt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.spacesta
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short spacesta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.face
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.safequestion
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short safequestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.safeanswer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String safeanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.jointime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer jointime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.joinip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String joinip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.logintime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.loginip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.checkmail
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Short checkmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.mtype
     *
     * @return the value of guanwang_xiduweb.mtype
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.mtype
     *
     * @param mtype the value for guanwang_xiduweb.mtype
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.pwd
     *
     * @return the value of guanwang_xiduweb.pwd
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.pwd
     *
     * @param pwd the value for guanwang_xiduweb.pwd
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.uname
     *
     * @return the value of guanwang_xiduweb.uname
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.uname
     *
     * @param uname the value for guanwang_xiduweb.uname
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.sex
     *
     * @return the value of guanwang_xiduweb.sex
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.sex
     *
     * @param sex the value for guanwang_xiduweb.sex
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.rank
     *
     * @return the value of guanwang_xiduweb.rank
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.rank
     *
     * @param rank the value for guanwang_xiduweb.rank
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setRank(Short rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.uptime
     *
     * @return the value of guanwang_xiduweb.uptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.uptime
     *
     * @param uptime the value for guanwang_xiduweb.uptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setUptime(Integer uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.exptime
     *
     * @return the value of guanwang_xiduweb.exptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getExptime() {
        return exptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.exptime
     *
     * @param exptime the value for guanwang_xiduweb.exptime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setExptime(Short exptime) {
        this.exptime = exptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.money
     *
     * @return the value of guanwang_xiduweb.money
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.money
     *
     * @param money the value for guanwang_xiduweb.money
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.email
     *
     * @return the value of guanwang_xiduweb.email
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.email
     *
     * @param email the value for guanwang_xiduweb.email
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.scores
     *
     * @return the value of guanwang_xiduweb.scores
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.scores
     *
     * @param scores the value for guanwang_xiduweb.scores
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setScores(Integer scores) {
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.matt
     *
     * @return the value of guanwang_xiduweb.matt
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getMatt() {
        return matt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.matt
     *
     * @param matt the value for guanwang_xiduweb.matt
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setMatt(Short matt) {
        this.matt = matt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.spacesta
     *
     * @return the value of guanwang_xiduweb.spacesta
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getSpacesta() {
        return spacesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.spacesta
     *
     * @param spacesta the value for guanwang_xiduweb.spacesta
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setSpacesta(Short spacesta) {
        this.spacesta = spacesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.face
     *
     * @return the value of guanwang_xiduweb.face
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.face
     *
     * @param face the value for guanwang_xiduweb.face
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.safequestion
     *
     * @return the value of guanwang_xiduweb.safequestion
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getSafequestion() {
        return safequestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.safequestion
     *
     * @param safequestion the value for guanwang_xiduweb.safequestion
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setSafequestion(Short safequestion) {
        this.safequestion = safequestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.safeanswer
     *
     * @return the value of guanwang_xiduweb.safeanswer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getSafeanswer() {
        return safeanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.safeanswer
     *
     * @param safeanswer the value for guanwang_xiduweb.safeanswer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setSafeanswer(String safeanswer) {
        this.safeanswer = safeanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.jointime
     *
     * @return the value of guanwang_xiduweb.jointime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getJointime() {
        return jointime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.jointime
     *
     * @param jointime the value for guanwang_xiduweb.jointime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setJointime(Integer jointime) {
        this.jointime = jointime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.joinip
     *
     * @return the value of guanwang_xiduweb.joinip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getJoinip() {
        return joinip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.joinip
     *
     * @param joinip the value for guanwang_xiduweb.joinip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setJoinip(String joinip) {
        this.joinip = joinip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.logintime
     *
     * @return the value of guanwang_xiduweb.logintime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.logintime
     *
     * @param logintime the value for guanwang_xiduweb.logintime
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.loginip
     *
     * @return the value of guanwang_xiduweb.loginip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.loginip
     *
     * @param loginip the value for guanwang_xiduweb.loginip
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.checkmail
     *
     * @return the value of guanwang_xiduweb.checkmail
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Short getCheckmail() {
        return checkmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.checkmail
     *
     * @param checkmail the value for guanwang_xiduweb.checkmail
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setCheckmail(Short checkmail) {
        this.checkmail = checkmail;
    }
}