package cn.entity.guanwang;

public class GW_XiduWebWithBLOBs extends GW_XiduWeb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.referer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.linksource
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String linksource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.referer
     *
     * @return the value of guanwang_xiduweb.referer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.referer
     *
     * @param referer the value for guanwang_xiduweb.referer
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setReferer(String referer) {
        this.referer = referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.linksource
     *
     * @return the value of guanwang_xiduweb.linksource
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getLinksource() {
        return linksource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.linksource
     *
     * @param linksource the value for guanwang_xiduweb.linksource
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setLinksource(String linksource) {
        this.linksource = linksource;
    }
}