package cn.entity.guanwang;

public class GW_XiduWebKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.mid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guanwang_xiduweb.userid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.mid
     *
     * @return the value of guanwang_xiduweb.mid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.mid
     *
     * @param mid the value for guanwang_xiduweb.mid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guanwang_xiduweb.userid
     *
     * @return the value of guanwang_xiduweb.userid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guanwang_xiduweb.userid
     *
     * @param userid the value for guanwang_xiduweb.userid
     *
     * @mbggenerated Mon Sep 05 15:40:18 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}